#!/bin/sh

wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/data.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/House Inventory.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/House Listings.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/House Price.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/House Rents.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Unit Inventory.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Unit Listings.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Unit Price.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Unit Rents.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Vacancy Rates.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/TownhouseBA.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/HouseBA.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/UnitBA.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/House Price Segments.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Unit Price Segments.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Summary.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Explore.csv"
wget --timestamping --directory-prefix public "https://storage.googleapis.com/suburbtrends-map-dev/Clusters.csv"
